---
- name: Check if k3s agent is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Install k3s agent and join cluster
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.29.4+k3s1" K3S_URL=https://10.0.1.216:6443 K3S_TOKEN={{ hostvars['k3s_token_holder']['k3s_token'] }} sh -s - agent
  when: not k3s_installed.stat.exists

- name: Ensure k3s-agent service is running
  service:
    name: k3s-agent
    state: started
    enabled: true