[control_plane]
phoenix-cp ansible_host=13.60.59.175 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[workers]
phoenix-worker-1 ansible_host=13.60.6.100 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
phoenix-worker-2 ansible_host=13.62.45.183 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[k3s_cluster:children]
control_plane
workers